name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GREETING: "Hello"
      USER_NAME: "onkar"

    steps:
      - name: Print variables
        run: echo "${{ env.GREETING }} ${{ env.USER_NAME }}! Welcome to GitHub Actions."

      
