name: My Workflow

on:
  push:
    branches:
      - main

env:
  MY_VARIABLE: ${{ vars.USER_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Variable
      run:  echo $MY_VARIABLE
