name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GREETING: "Hello"
      USER_NAME: "onkar"

    steps:
      - name: Print Variable
        run: echo "Hi am ${{ vars.USER_NAME }} Welcome to GitHub Actions."
      
      - name: Execute My Script
        run: | 
          chmod +x script.sh
          bash ./script.sh
