name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GREETING: "Hello"
      USER_NAME: "onkar"

    steps:
      - name: Print Greeting
        run: echo "${{ env.GREETING }} ${{ env.USER_NAME }}! Welcome to GitHub Actions."

      - name: Print Working Directory
        run: |
          pwd
          ls -l

      - name: Run Custom Script
        run: |
          bash ./gitaction_poc2/myscript.sh
